/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

const filePath = "/3d/books.glb";

useGLTF.preload(filePath);

type GLTFResult = GLTF & {
  nodes: {
    Cube011: THREE.Mesh;
    Cube011_1: THREE.Mesh;
    Cube012: THREE.Mesh;
    Cube012_1: THREE.Mesh;
    Cube018: THREE.Mesh;
    Cube018_1: THREE.Mesh;
    Cube021: THREE.Mesh;
    Cube021_1: THREE.Mesh;
    Cube028: THREE.Mesh;
    Cube028_1: THREE.Mesh;
    Cube029: THREE.Mesh;
    Cube029_1: THREE.Mesh;
    Cube030: THREE.Mesh;
    Cube030_1: THREE.Mesh;
    Cube031: THREE.Mesh;
    Cube031_1: THREE.Mesh;
    Cube032: THREE.Mesh;
    Cube032_1: THREE.Mesh;
    Cube033: THREE.Mesh;
    Cube033_1: THREE.Mesh;
    Cube034: THREE.Mesh;
    Cube034_1: THREE.Mesh;
    Cube035: THREE.Mesh;
    Cube035_1: THREE.Mesh;
    Cube036: THREE.Mesh;
    Cube036_1: THREE.Mesh;
    Cube037: THREE.Mesh;
    Cube037_1: THREE.Mesh;
    Cube038: THREE.Mesh;
    Cube038_1: THREE.Mesh;
    Cube039: THREE.Mesh;
    Cube039_1: THREE.Mesh;
    Cube040: THREE.Mesh;
    Cube040_1: THREE.Mesh;
    Cube041: THREE.Mesh;
    Cube041_1: THREE.Mesh;
  };
  materials: {
    BookColorRed: THREE.MeshStandardMaterial;
    BookPageColor: THREE.MeshStandardMaterial;
    YellowColor: THREE.MeshStandardMaterial;
    BookColorBlue3: THREE.MeshStandardMaterial;
    BookColorGeen: THREE.MeshStandardMaterial;
    BookColorBlue: THREE.MeshStandardMaterial;
    BookColorBlue2: THREE.MeshStandardMaterial;
  };
};

const Books = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF(filePath) as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group position={[0.308, -0.717, -1.468]} scale={[1.235, 1.034, 1.235]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={materials.BookColorRed}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_1.geometry}
          material={materials.BookPageColor}
        />
      </group>
      <group
        position={[0.308, -0.673, -1.468]}
        rotation={[0, -0.189, 0]}
        scale={[1.235, 0.746, 1.235]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012.geometry}
          material={materials.YellowColor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_1.geometry}
          material={materials.BookPageColor}
        />
      </group>
      <group
        position={[0.308, -0.646, -1.468]}
        rotation={[0, 0.076, 0]}
        scale={[0.748, 0.304, 0.748]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018.geometry}
          material={materials.BookColorBlue3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_1.geometry}
          material={materials.BookPageColor}
        />
      </group>
      <group
        position={[-1.037, -0.12, -1.611]}
        rotation={[0, 0.177, 0]}
        scale={[1.067, 0.893, 1.067]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021.geometry}
          material={materials.BookColorGeen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021_1.geometry}
          material={materials.BookPageColor}
        />
      </group>
      <group
        position={[-0.297, 0.07, -1.613]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.425, 1.768, 1.425]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028.geometry}
          material={materials.BookColorRed}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028_1.geometry}
          material={materials.BookPageColor}
        />
      </group>
      <group
        position={[-0.399, 0.07, -1.613]}
        rotation={[1.577, -0.21, -1.54]}
        scale={[1.425, 0.694, 1.425]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube029.geometry}
          material={materials.YellowColor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube029_1.geometry}
          material={materials.BookPageColor}
        />
      </group>
      <group
        position={[-1.601, 0.07, 1.45]}
        rotation={[1.571, 0, Math.PI]}
        scale={[1.425, 1.768, 1.425]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030.geometry}
          material={materials.BookColorBlue}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030_1.geometry}
          material={materials.BookPageColor}
        />
      </group>
      <group
        position={[-1.601, 0.069, 1.374]}
        rotation={[1.571, 0, Math.PI]}
        scale={[1.425, 1.337, 1.425]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube031.geometry}
          material={materials.BookColorBlue2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube031_1.geometry}
          material={materials.BookPageColor}
        />
      </group>
      <group
        position={[-1.601, 0.051, 1.311]}
        rotation={[1.571, 0, Math.PI]}
        scale={[1.425, 1.17, 1.302]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube032.geometry}
          material={materials.BookColorRed}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube032_1.geometry}
          material={materials.BookPageColor}
        />
      </group>
      <group
        position={[-1.601, -0.113, 0.805]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.425, 1.17, 1.425]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033.geometry}
          material={materials.BookColorRed}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_1.geometry}
          material={materials.BookPageColor}
        />
      </group>
      <group
        position={[-1.601, -0.054, 0.805]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.425, 1.17, 1.125]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube034.geometry}
          material={materials.BookColorBlue2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube034_1.geometry}
          material={materials.BookPageColor}
        />
      </group>
      <group
        position={[-1.601, 0.004, 0.805]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.425, 1.17, 1.267]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035.geometry}
          material={materials.YellowColor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_1.geometry}
          material={materials.BookPageColor}
        />
      </group>
      <group
        position={[-1.601, 0.742, 0.626]}
        rotation={[1.571, 0, Math.PI]}
        scale={[1.425, 1.768, 1.425]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube036.geometry}
          material={materials.BookColorGeen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube036_1.geometry}
          material={materials.BookPageColor}
        />
      </group>
      <group
        position={[-1.601, 0.718, 0.549]}
        rotation={[1.571, 0, Math.PI]}
        scale={[1.425, 1.337, 1.263]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube037.geometry}
          material={materials.BookColorRed}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube037_1.geometry}
          material={materials.BookPageColor}
        />
      </group>
      <group
        position={[-1.601, 0.742, 0.487]}
        rotation={[1.571, 0, Math.PI]}
        scale={[1.425, 1.17, 1.425]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube038.geometry}
          material={materials.BookColorBlue2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube038_1.geometry}
          material={materials.BookPageColor}
        />
      </group>
      <group
        position={[-1.601, 0.739, 0.423]}
        rotation={[1.571, 0, Math.PI]}
        scale={[1.425, 1.413, 1.404]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube039.geometry}
          material={materials.YellowColor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube039_1.geometry}
          material={materials.BookPageColor}
        />
      </group>
      <group
        position={[-1.601, 0.742, 0.69]}
        rotation={[1.571, 0, Math.PI]}
        scale={[1.425, 0.839, 1.425]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube040.geometry}
          material={materials.BookColorRed}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube040_1.geometry}
          material={materials.BookPageColor}
        />
      </group>
      <group
        position={[-1.601, 0.69, 0.754]}
        rotation={[1.43, 0, Math.PI]}
        scale={[1.425, 0.835, 1.099]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube041.geometry}
          material={materials.BookColorBlue2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube041_1.geometry}
          material={materials.BookPageColor}
        />
      </group>
    </group>
  );
};

export default Books;
