/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

const filePath = "/3d/carpet.glb";

useGLTF.preload(filePath);

type GLTFResult = GLTF & {
  nodes: {
    Carpet: THREE.Mesh;
  };
  materials: {
    CarpetColor: THREE.MeshStandardMaterial;
  };
};

const Carpet = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF(filePath) as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Carpet.geometry}
        material={materials.CarpetColor}
        position={[0.565, -1.79, 0.588]}
        scale={1.242}
      />
    </group>
  );
};

export default Carpet;
