/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

const filePath = "/3d/chair.glb";

useGLTF.preload(filePath);

type GLTFResult = GLTF & {
  nodes: {
    Chair: THREE.Mesh;
    ChairLeg1: THREE.Mesh;
    ChairLeg2: THREE.Mesh;
    ChairLegWheel1: THREE.Mesh;
    ChairLegWheel2: THREE.Mesh;
    ChairLegWheel3: THREE.Mesh;
    ChairLegWheel4: THREE.Mesh;
    ChairLegWheel5: THREE.Mesh;
    ChairLegWheel6: THREE.Mesh;
  };
  materials: {
    YellowColor: THREE.MeshStandardMaterial;
    ChairLegMaterial: THREE.MeshStandardMaterial;
  };
};

const Chair = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF(filePath) as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair.geometry}
        material={materials.YellowColor}
        position={[0.699, -0.93, -0.274]}
        rotation={[0, -0.525, 0]}
        scale={[1.137, 1.242, 1]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ChairLeg1.geometry}
          material={materials.ChairLegMaterial}
          position={[0, -0.399, -0.071]}
          scale={[0.88, 0.805, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ChairLeg2.geometry}
          material={materials.ChairLegMaterial}
          position={[0, -0.538, -0.071]}
          scale={[0.215, 0.805, 0.244]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ChairLegWheel1.geometry}
          material={materials.ChairLegMaterial}
          position={[0.342, -0.658, -0.071]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={[0.034, 0.03, 0.038]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ChairLegWheel2.geometry}
          material={materials.ChairLegMaterial}
          position={[0.174, -0.658, -0.414]}
          rotation={[-3.022, 1.24, 1.43]}
          scale={[0.034, 0.029, 0.038]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ChairLegWheel3.geometry}
          material={materials.ChairLegMaterial}
          position={[-0.173, -0.658, -0.412]}
          rotation={[-3.022, 1.24, 1.43]}
          scale={[0.034, 0.029, 0.038]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ChairLegWheel4.geometry}
          material={materials.ChairLegMaterial}
          position={[-0.347, -0.658, -0.07]}
          rotation={[-3.041, 0.903, 1.462]}
          scale={[0.034, 0.028, 0.04]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ChairLegWheel5.geometry}
          material={materials.ChairLegMaterial}
          position={[-0.171, -0.658, 0.267]}
          rotation={[-3.017, 1.402, 1.43]}
          scale={[0.034, 0.03, 0.038]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ChairLegWheel6.geometry}
          material={materials.ChairLegMaterial}
          position={[0.172, -0.658, 0.268]}
          rotation={[-3.017, 1.402, 1.43]}
          scale={[0.034, 0.03, 0.038]}
        />
      </mesh>
    </group>
  );
};

export default Chair;
