/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

const filePath = "/3d/flower.glb";

useGLTF.preload(filePath);

type GLTFResult = GLTF & {
  nodes: {
    Flower: THREE.Mesh;
    FlowerLeaf1: THREE.Mesh;
    FlowerLeaf10: THREE.Mesh;
    FlowerLeaf11: THREE.Mesh;
    FlowerLeaf12: THREE.Mesh;
    FlowerLeaf2: THREE.Mesh;
    FlowerLeaf3: THREE.Mesh;
    FlowerLeaf4: THREE.Mesh;
    FlowerLeaf5: THREE.Mesh;
    FlowerLeaf6: THREE.Mesh;
    FlowerLeaf7: THREE.Mesh;
    FlowerLeaf8: THREE.Mesh;
    FlowerLeaf9: THREE.Mesh;
  };
  materials: {
    BrownColor3: THREE.MeshStandardMaterial;
    GreenColor2: THREE.MeshPhysicalMaterial;
  };
};

const Flower = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF(filePath) as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Flower.geometry}
        material={materials.BrownColor3}
        position={[-1.368, -1.8, 1.751]}
        rotation={[0, 1.32, 0]}
        scale={1.491}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FlowerLeaf1.geometry}
          material={materials.GreenColor2}
          position={[-0.145, 0.237, 0.059]}
          rotation={[0.529, -1.086, 0.477]}
          scale={0.453}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FlowerLeaf10.geometry}
          material={materials.GreenColor2}
          position={[-0.01, 0.449, -0.097]}
          rotation={[2.904, 0.046, -3.131]}
          scale={[0.333, 0.627, 0.357]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FlowerLeaf11.geometry}
          material={materials.GreenColor2}
          position={[0.074, 0.424, 0.018]}
          rotation={[1.137, 1.309, -1.124]}
          scale={[0.333, 0.759, 0.362]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FlowerLeaf12.geometry}
          material={materials.GreenColor2}
          position={[-0.014, 0.397, 0.113]}
          rotation={[0.258, 0.396, -0.101]}
          scale={[0.333, 0.627, 0.357]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FlowerLeaf2.geometry}
          material={materials.GreenColor2}
          position={[-0.093, 0.319, -0.109]}
          rotation={[2.854, -0.596, 2.977]}
          scale={0.453}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FlowerLeaf3.geometry}
          material={materials.GreenColor2}
          position={[0.093, 0.293, -0.057]}
          rotation={[2.708, 0.976, -2.776]}
          scale={0.453}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FlowerLeaf4.geometry}
          material={materials.GreenColor2}
          position={[0.079, 0.242, 0.118]}
          rotation={[0.467, 1.021, -0.406]}
          scale={0.453}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FlowerLeaf5.geometry}
          material={materials.GreenColor2}
          position={[-0.078, 0.332, 0.086]}
          rotation={[0.29, -0.604, 0.168]}
          scale={[0.333, 0.427, 0.339]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FlowerLeaf6.geometry}
          material={materials.GreenColor2}
          position={[-0.106, 0.417, -0.041]}
          rotation={[2.62, -1.079, 2.673]}
          scale={[0.333, 0.549, 0.349]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FlowerLeaf7.geometry}
          material={materials.GreenColor2}
          position={[0.032, 0.373, -0.076]}
          rotation={[2.873, 0.485, -3.014]}
          scale={[0.333, 0.484, 0.344]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FlowerLeaf8.geometry}
          material={materials.GreenColor2}
          position={[0.087, 0.32, 0.042]}
          rotation={[1.653, 1.333, -1.655]}
          scale={[0.333, 0.403, 0.338]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FlowerLeaf9.geometry}
          material={materials.GreenColor2}
          position={[-0.117, 0.391, -0.023]}
          rotation={[2.339, -1.238, 2.367]}
          scale={[0.333, 0.627, 0.357]}
        />
      </mesh>
    </group>
  );
};

export default Flower;
