/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

const filePath = "/3d/shelf.glb";

useGLTF.preload(filePath);

type GLTFResult = GLTF & {
  nodes: {
    TableTop2: THREE.Mesh;
    TableTop3: THREE.Mesh;
    TableTop4: THREE.Mesh;
  };
  materials: {
    BrownColor: THREE.MeshStandardMaterial;
  };
};

const Shelf = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF(filePath) as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TableTop2.geometry}
        material={materials.BrownColor}
        position={[-0.845, -0.2, -1.621]}
        scale={[0.766, 1, 0.392]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TableTop3.geometry}
        material={materials.BrownColor}
        position={[-1.616, -0.2, 0.937]}
        rotation={[0, 1.571, 0]}
        scale={[0.766, 1, 0.392]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TableTop4.geometry}
        material={materials.BrownColor}
        position={[-1.616, 0.475, 0.937]}
        rotation={[0, 1.571, 0]}
        scale={[0.766, 1, 0.392]}
      />
    </group>
  );
};

export default Shelf;
